Repository basedosdados/pipelines, pull requests merged in 2023-04, with the labels that each got.

#284 [feat] adds columns to the `tables` table
  pipelines/datasets/br_bd_metadados/flows.py
  pipelines/datasets/br_bd_metadados/schedules.py
  pipelines/datasets/br_bd_metadados/tasks.py
  pipelines/datasets/br_bd_metadados/utils.py
Labels: enhancement

#286 [test] `br_inmet_bdmep`
  pipelines/constants.py
  pipelines/datasets/__init__.py
  pipelines/datasets/br_inmet_bdmep/__init__.py
  pipelines/datasets/br_inmet_bdmep/constants.py
  pipelines/datasets/br_inmet_bdmep/flows.py
  pipelines/datasets/br_inmet_bdmep/schedules.py
  pipelines/datasets/br_inmet_bdmep/tasks.py
  pipelines/datasets/br_inmet_bdmep/utils.py
  poetry.lock
Labels: conflict

#291 [feat] br_anatel_banda_larga_fixa
  pipelines/datasets/__init__.py
  pipelines/datasets/br_anatel_banda_larga_fixa/__init__.py
  pipelines/datasets/br_anatel_banda_larga_fixa/constants.py
  pipelines/datasets/br_anatel_banda_larga_fixa/flows.py
  pipelines/datasets/br_anatel_banda_larga_fixa/run.py
  pipelines/datasets/br_anatel_banda_larga_fixa/schedules.py
  pipelines/datasets/br_anatel_banda_larga_fixa/tasks.py
  pipelines/datasets/br_anatel_banda_larga_fixa/utils.py
Labels: enhancement, conflict
