Repository basedosdados/pipelines, pull requests merged in 2023-08, with the labels that each got.

#295 [dados] br_ms_cnes
  pipelines/datasets/__init__.py
  pipelines/datasets/br_ms_cnes/__init__.py
  pipelines/datasets/br_ms_cnes/constants.py
  pipelines/datasets/br_ms_cnes/flows.py
  pipelines/datasets/br_ms_cnes/schedules.py
  pipelines/datasets/br_ms_cnes/tasks.py
  pipelines/datasets/br_ms_cnes/utils.py
  pipelines/utils/tasks.py
  pipelines/utils/utils.py
  poetry.lock
  pyproject.toml
Labels: data, conflict

#429 fix to_partitions
  pipelines/datasets/br_anp_precos_combustiveis/schedules.py
  pipelines/utils/utils.py
Labels: bug

#407 [dados]: `br_mp_pep_cargos_funcoes`
  Dockerfile
  pipelines/datasets/__init__.py
  pipelines/datasets/br_mp_pep_cargos_funcoes/__init__.py
  pipelines/datasets/br_mp_pep_cargos_funcoes/constants.py
  pipelines/datasets/br_mp_pep_cargos_funcoes/flows.py
  pipelines/datasets/br_mp_pep_cargos_funcoes/schedules.py
  pipelines/datasets/br_mp_pep_cargos_funcoes/tasks.py
  pipelines/datasets/br_mp_pep_cargos_funcoes/utils.py
  poetry.lock
  pyproject.toml
Labels: conflict

#440 [fix] fix to_partitions()
  pipelines/utils/utils.py
Labels: bug
