Repository basedosdados/pipelines, pull requests merged in 2023-05, with the labels that each got.

#311 [test]br_bcb_agencia
  pipelines/datasets/__init__.py
  pipelines/datasets/br_bcb_agencia/__init__.py
  pipelines/datasets/br_bcb_agencia/constants.py
  pipelines/datasets/br_bcb_agencia/flows.py
  pipelines/datasets/br_bcb_agencia/schedules.py
  pipelines/datasets/br_bcb_agencia/tasks.py
  pipelines/datasets/br_bcb_agencia/utils.py
  pipelines/datasets/delete_flows/tasks.py
  poetry.lock
  pyproject.toml
Labels: data

#298 [feat] reading files with different names in `br_ibge_pnadc`
  pipelines/datasets/br_ibge_pnadc/schedules.py
  pipelines/datasets/br_ibge_pnadc/tasks.py
Labels: enhancement

#321 forcing deploy in prod
  pipelines/datasets/br_bd_indicadores/flows.py
Labels: bug

#312 [test] br_me_comex_stat
  pipelines/datasets/br_me_comex_stat/constants.py
  pipelines/datasets/br_me_comex_stat/flows.py
  pipelines/datasets/br_me_comex_stat/schedules.py
  pipelines/datasets/br_me_comex_stat/tasks.py
  pipelines/datasets/br_me_comex_stat/utils.py
Labels: data, conflict

#318 [feat] br_b3_cotacoes
  pipelines/datasets/__init__.py
  pipelines/datasets/br_b3_cotacoes/constants.py
  pipelines/datasets/br_b3_cotacoes/flows.py
  pipelines/datasets/br_b3_cotacoes/schedules.py
  pipelines/datasets/br_b3_cotacoes/tasks.py
  pipelines/datasets/br_b3_cotacoes/utils.py
Labels: pro
