Repository basedosdados/pipelines, pull requests merged in 2025-10, with the labels that each got.

#1260 [Update] br_ibge_pam
  models/br_ibge_pam/br_ibge_pam__lavoura_permanente.sql
  models/br_ibge_pam/br_ibge_pam__lavoura_temporaria.sql
  models/br_ibge_pam/lavoura_permanente/code/api_to_json.py
  models/br_ibge_pam/lavoura_permanente/code/json_to_parquet.py
  models/br_ibge_pam/lavoura_temporaria/code/api_to_json.py
  models/br_ibge_pam/lavoura_temporaria/code/json_to_parquet.py
Labels: test-dev-model, table-approve

#1264 [fix] br_ibge_pnadc
  models/br_ibge_pnadc/schema.yml
  pipelines/datasets/br_ibge_pnadc/constants.py
  pipelines/datasets/br_ibge_pnadc/flows.py
  pipelines/datasets/br_ibge_pnadc/schedules.py
  pipelines/datasets/br_ibge_pnadc/tasks.py
  pipelines/datasets/br_ibge_pnadc/utils.py
Labels: bug

#1266 Register ibge inflacao
  models/br_ibge_inpc/br_ibge_inpc__mes_brasil.sql
  models/br_ibge_inpc/br_ibge_inpc__mes_categoria_brasil.sql
  models/br_ibge_inpc/br_ibge_inpc__mes_categoria_municipio.sql
  models/br_ibge_inpc/br_ibge_inpc__mes_categoria_rm.sql
  models/br_ibge_inpc/schema.yml
  models/br_ibge_ipca/br_ibge_ipca__mes_brasil.sql
  models/br_ibge_ipca/br_ibge_ipca__mes_categoria_brasil.sql
  models/br_ibge_ipca/br_ibge_ipca__mes_categoria_municipio.sql
  models/br_ibge_ipca/br_ibge_ipca__mes_categoria_rm.sql
  models/br_ibge_ipca/schema.yml
  models/br_ibge_ipca15/br_ibge_ipca15__mes_brasil.sql
  models/br_ibge_ipca15/br_ibge_ipca15__mes_categoria_brasil.sql
  models/br_ibge_ipca15/br_ibge_ipca15__mes_categoria_municipio.sql
  models/br_ibge_ipca15/br_ibge_ipca15__mes_categoria_rm.sql
  models/br_ibge_ipca15/schema.yml
Labels: table-approve
