Repository basedosdados/pipelines, pull requests merged in 2025-09, with the labels that each got.

#1196 [Refactor] br_rj_isp_estatisticas_seguranca
  models/br_rj_isp_estatisticas_seguranca/br_rj_isp_estatisticas_seguranca__armas_apreendidas_mensal.sql
  models/br_rj_isp_estatisticas_seguranca/br_rj_isp_estatisticas_seguranca__armas_fogo_apreendidas_mensal.sql
  models/br_rj_isp_estatisticas_seguranca/br_rj_isp_estatisticas_seguranca__evolucao_mensal_cisp.sql
  models/br_rj_isp_estatisticas_seguranca/br_rj_isp_estatisticas_seguranca__evolucao_mensal_municipio.sql
  models/br_rj_isp_estatisticas_seguranca/br_rj_isp_estatisticas_seguranca__evolucao_mensal_uf.sql
  models/br_rj_isp_estatisticas_seguranca/br_rj_isp_estatisticas_seguranca__evolucao_mensal_upp.sql
  models/br_rj_isp_estatisticas_seguranca/br_rj_isp_estatisticas_seguranca__evolucao_policial_morto_servico_mensal.sql
  models/br_rj_isp_estatisticas_seguranca/br_rj_isp_estatisticas_seguranca__feminicidio_mensal_cisp.sql
  models/br_rj_isp_estatisticas_seguranca/br_rj_isp_estatisticas_seguranca__relacao_cisp_aisp_risp.sql
  models/br_rj_isp_estatisticas_seguranca/br_rj_isp_estatisticas_seguranca__taxa_evolucao_anual_municipio.sql
  models/br_rj_isp_estatisticas_seguranca/br_rj_isp_estatisticas_seguranca__taxa_evolucao_anual_uf.sql
  models/br_rj_isp_estatisticas_seguranca/br_rj_isp_estatisticas_seguranca__taxa_evolucao_mensal_municipio.sql
  models/br_rj_isp_estatisticas_seguranca/br_rj_isp_estatisticas_seguranca__taxa_evolucao_mensal_uf.sql
  models/br_rj_isp_estatisticas_seguranca/br_rj_isp_estatisticas_seguranca__taxa_letalidade.sql
  models/br_rj_isp_estatisticas_seguranca/schema.yml
  pipelines/datasets/br_rj_isp_estatisticas_seguranca/constants.py
  pipelines/datasets/br_rj_isp_estatisticas_seguranca/flows.py
  pipelines/datasets/br_rj_isp_estatisticas_seguranca/schedules.py
  pipelines/datasets/br_rj_isp_estatisticas_seguranca/tasks.py
  pipelines/utils/crawler_isp/constants.py
  pipelines/utils/crawler_isp/flows.py
  pipelines/utils/crawler_isp/tasks.py
  pipelines/utils/crawler_isp/utils.py
Labels: table-approve

#1206 [fix] br_me_cnpj - dicionário
  models/br_me_cnpj/br_me_cnpj__dicionario.sql
Labels: test-dev-model, table-approve

#1244 [fix] tests_br_denatran_frota
  pipelines/datasets/br_denatran_frota/tasks.py
  pipelines/datasets/br_denatran_frota/tests/tasks.py
  pipelines/datasets/br_denatran_frota/tests/utils.py
Labels: bug

#1247 [Reactive/Refactor] br_ms_sia.producao_ambulatorial
  models/br_ms_sia/br_ms_sia__producao_ambulatorial.sql
  pipelines/datasets/br_ms_sia/flows.py
Labels: test-dev-model

#1243 [fix] memory_limit_br_rf_cno
  pipelines/datasets/br_rf_cno/flows.py
Labels: bug
